spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #  mapper-locations: classpath*:com\batman\shard\demo\dao\**\*.xml
  mapper-locations: classpath:mapper/*.xml